#!/bin/bash
# Latte Loader provisioning with Precompiled Native Binary and Custom Workloads
set -xe

# Redirect stdout/stderr to a log file for debugging
exec > >(tee /var/log/loader-setup.log | logger -t user-data -s 2>/dev/null) 2>&1

echo "========================================="
echo " Starting Latte Loader node provisioning"
echo "========================================="

# 1. Install dependencies
apt-get update && apt-get install -y curl wget git htop iotop build-essential

# 1a. OS tuning for high new-connection-per-second connection floods.
# A connection storm opens and tears down huge numbers of short-lived TCP+CQL
# sessions. The client side is normally limited first by (a) open file
# descriptors, (b) the ephemeral source-port range, and (c) sockets stuck in
# TIME_WAIT. Widen all three so a single loader can sustain tens of thousands
# of new connections/s.
echo "Applying connection-flood OS tuning..."
cat <<'SYSCTL' > /etc/sysctl.d/99-latte-connflood.conf
# Maximize usable ephemeral source ports (~64k - 1024 = ~64.5k per loader)
net.ipv4.ip_local_port_range = 1024 65535
# Recycle TIME_WAIT sockets quickly so ports free up for new connections
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_fin_timeout = 5
# Larger listen/accept and SYN backlogs
net.core.somaxconn = 65535
net.ipv4.tcp_max_syn_backlog = 65535
net.core.netdev_max_backlog = 65535
# Allow many sockets in TIME_WAIT without dropping them
net.ipv4.tcp_max_tw_buckets = 2000000
SYSCTL
sysctl --system || true

# Raise file-descriptor limits (each open connection consumes one fd).
cat <<'LIMITS' > /etc/security/limits.d/99-latte-nofile.conf
*       soft    nofile  1048576
*       hard    nofile  1048576
root    soft    nofile  1048576
root    hard    nofile  1048576
LIMITS
# Ensure systemd-launched and interactive shells also get the high limit
echo "DefaultLimitNOFILE=1048576" >> /etc/systemd/system.conf
mkdir -p /etc/systemd/user.conf.d
echo -e "[Manager]\nDefaultLimitNOFILE=1048576" > /etc/systemd/user.conf.d/nofile.conf

# 2. Download and install Precompiled Latte Release Binary (v0.49.0-scylladb)
LATTE_VERSION="0.49.0-scylladb"
echo "Downloading precompiled Latte binary..."
wget https://github.com/scylladb/latte/releases/download/$${LATTE_VERSION}/latte-$${LATTE_VERSION}--ubuntu-24.04 -O /usr/local/bin/latte
chmod +x /usr/local/bin/latte

# Verify installation
latte --version

# 3. Create workloads directory for ubuntu user
mkdir -p /home/ubuntu/workloads

# The embedded workload files are gzip+base64-compressed (to stay under the
# 16 KB EC2 user_data limit). Decode each back to its original form. NOTE: the
# connection storm is generated by `scylla perf-cql-raw` (installed from the
# Scylla apt repo below), so no custom storm binary is shipped to the loader.

# Write workloads/workload.rn to loader
base64 -d <<'EOF' | gunzip > /home/ubuntu/workloads/workload.rn
${workload_rn_content}
EOF

# Write workloads/run_benchmark.sh to loader
base64 -d <<'EOF' | gunzip > /home/ubuntu/workloads/run_benchmark.sh
${run_benchmark_content}
EOF

# Make scripts executable and fix ownership
chmod +x /home/ubuntu/workloads/run_benchmark.sh
chown -R ubuntu:ubuntu /home/ubuntu/workloads

# 4. Install ScyllaDB (for the `scylla perf-cql-raw` connection-storm tool).
# The connection storm is generated by ScyllaDB's own native raw-CQL benchmark
# (`scylla perf-cql-raw --workload connect`), which opens/handshakes/closes real
# CQL connections with proper deterministic teardown and high per-shard
# concurrency — the correct way to drive scylla_transport_connections_shed. We
# install the SAME scylla package the DB nodes use (deps resolved natively for
# Ubuntu; matches the cluster version) but we DO NOT enable/start scylla-server:
# only the binary is used, as a client.
echo "Installing ScyllaDB (client-only, for perf-cql-raw connection storm)..."
apt-get install -y apt-transport-https gnupg2
curl -sSfLo /etc/apt/sources.list.d/scylla.list https://s3.amazonaws.com/downloads.scylladb.com/deb/ubuntu/scylla-${scylla_version}.list
# Same expired-2024-GPG workaround the nodes use: trust the repo directly.
sed -i 's/signed-by=\/etc\/apt\/keyrings\/scylladb.gpg/trusted=yes/g' /etc/apt/sources.list.d/scylla.list
apt-get update
# Install scylla but keep it stopped/disabled — we only want the binary.
# Masking scylla-server BEFORE install prevents the package postinst from
# starting a (misconfigured, storage-less) node on this loader.
systemctl mask scylla-server || true
DEBIAN_FRONTEND=noninteractive apt-get install -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" scylla || \
    DEBIAN_FRONTEND=noninteractive apt-get install -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" scylla-server
systemctl disable --now scylla-server 2>/dev/null || true
scylla --version || echo "WARNING: scylla binary not runnable on loader"

# 4a. Fake ScyllaDB REST endpoint for perf-cql-raw's compaction pre-check.
# perf-cql-raw's `connect` workload calls wait_for_compactions(), which polls
#   http://<remote-host>:10000/compaction_manager/compactions
# and refuses to start until it returns "[]". Against a REAL cluster node that
# endpoint is (a) bound to 127.0.0.1 on the node and firewalled (unreachable),
# and (b) once steady load runs, returns a NON-empty compaction list, so the
# poll would time out (~60s) and abort the storm. We therefore intercept that
# poll ON THE LOADER: a tiny local HTTP server on 127.0.0.1:10000 always answers
# "[]", and (at storm time) run_benchmark.sh adds an iptables OUTPUT REDIRECT of
# each <scylla-ip>:10000 to this local server. Storm CQL traffic (:9042) is NOT
# touched and goes straight to the real node.
cat <<'FAKEREST' > /usr/local/bin/fake-compaction-endpoint.py
#!/usr/bin/env python3
# Minimal HTTP server that answers every request with an empty JSON array "[]".
# Used to satisfy perf-cql-raw's wait_for_compactions() pre-check locally so a
# connection storm can start even while the real cluster is compacting.
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

class H(BaseHTTPRequestHandler):
    def _ok(self):
        body = b"[]"
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        try:
            self.wfile.write(body)
        except BrokenPipeError:
            pass
    def do_GET(self):
        self._ok()
    def do_POST(self):
        self._ok()
    def log_message(self, *a):
        pass  # stay quiet

if __name__ == "__main__":
    # Bind on 127.0.0.1:10000 (the iptables REDIRECT target on the loader).
    ThreadingHTTPServer(("127.0.0.1", 10000), H).serve_forever()
FAKEREST
chmod +x /usr/local/bin/fake-compaction-endpoint.py

cat <<'FAKEUNIT' > /etc/systemd/system/fake-compaction-endpoint.service
[Unit]
Description=Fake ScyllaDB compaction REST endpoint (returns [] for perf-cql-raw)
After=network.target

[Service]
ExecStart=/usr/bin/python3 /usr/local/bin/fake-compaction-endpoint.py
Restart=always
RestartSec=2

[Install]
WantedBy=multi-user.target
FAKEUNIT
systemctl daemon-reload
systemctl enable --now fake-compaction-endpoint.service || true

# Allow the OUTPUT-chain REDIRECT of remote :10000 traffic to reach the local
# loopback listener (127/8 as a route target is disabled by default).
cat <<'SYSCTL2' > /etc/sysctl.d/99-storm-route-localnet.conf
net.ipv4.conf.all.route_localnet = 1
SYSCTL2
sysctl --system || true

echo "========================================="
echo " Loader Node fully provisioned!"
echo "========================================="
